// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axjwkwkoksognhxycvvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4andrd2tva3NvZ25oeHljdnZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NzU5NzYsImV4cCI6MjA5MDQ1MTk3Nn0.M8UixVKJGMANBbE5m9X9QV0B5qC1tehYFcG6dx6IPdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});